### PR TITLE
Add exception_field parameter

### PR DESCRIPTION
**Pull request by doojonio**
Hello! We like to use your module in our application but we need to reuse exception field for our own purposes.
I think we have 2 ways:
- do not set exception field if already exists
- or add exception_field parameter which disables exception field

I have done second way. Can your review it please?

### CODE REVIEW

**Comment by Colin-b** [comment]
Hello @doojonio , this is a proper use case indeed. Could you please instead provide a exception_field_name parameter as string, defaulting to the current value ("exception") and that you could set to None/empty string to disable? It would allow both renaming and disabling with a single parameter. You would then also have to add an additional test case to test that you can rename the field as well.

Thanks again

**Comment by doojonio** [comment]
Added exception_field_name

**Comment by Colin-b** [comment]
Thanks, for some reason one test case is failing with python 3.10, I'll try to find some time to fix it

**Comment by Colin-b** [comment]
Version 0.3.0 is now available on pypi. Thanks a lot for your contribution !

FYI There is apparently an undocumented regression in latest python 3.10 version: msecs is now only providing milliseconds without more precision.

**Pull request merged**
